### ISSUE TITLE
gnome-control-center fails to launch

### ISSUE THREAD

**Issue by markstos** [Drakulix/sway-gnome#5]
Since a focus of this project has to do with GNOME settings, I expected to be able to launch `gnome-control-center`, but it fails:

```
ERROR:../shell/cc-shell-model.c:458:cc_shell_model_set_panel_visibility: assertion failed: (valid)
Bail out! ERROR:../shell/cc-shell-model.c:458:cc_shell_model_set_panel_visibility: assertion failed: (valid)
fish: “gnome-control-center” terminated by signal SIGABRT (Abort)
```

It turns out this a "known issue" and even perhaps "intended behavior" when gnome-control-center is running outside of GNOME:

https://gitlab.gnome.org/GNOME/gnome-control-center/issues/248

Yet, Regolith has this working for i3 so I believe it should be possible with Sway as well. 

Is `gnome-control-center` launching for other users of this module?  Perhaps enabling or disabling of some the "gsd" services included here makes a difference?

**Comment by Drakulix** [comment]
To launch gnome-control-center you need to have set the environment variable `XDG_CURRENT_DESKTOP` to `GNOME`. (intended behavior, but quite stupid imho.)

This should been taken care of by [`.config/sway/env`](https://github.com/Drakulix/sway-gnome/blob/master/sway/env) (as loaded by [`sway.service`](https://github.com/Drakulix/sway-gnome/blob/master/systemd/user/sway.service#L10)).

Maybe the variable is dropped or changed by your launcher? Open a terminal and check if it is there and if launching gnome-control-center works from it.

**Comment by markstos** [comment]
Maybe I didn't manually copy the env file over. I'll check tonight.

**Comment by markstos** [comment]
My `env` file was not in the right place. My PR #7 will turn this condition into a failure, allowing users to identify and resolve the issue.

Good news: gnome-control-center launches after this change.
